apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arch-suite.fullname" . }}-backend-config
  labels:
    {{- include "arch-suite.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  MONGODB_URI: {{ if .Values.mongodb.enabled }}mongodb://{{ include "arch-suite.fullname" . }}-mongodb:27017/arch-suite{{ else }}mongodb://mongodb-service:27017/arch-suite{{ end }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  JWT_EXPIRE: {{ .Values.config.jwtExpire | quote }}
