apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-suite.fullname" . }}-backend
  labels:
    {{- include "arch-suite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arch-suite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-suite.fullname" . }}-frontend
  labels:
    {{- include "arch-suite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arch-suite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
